### ISSUE TITLE
Paypal sandbox not working

### ISSUE THREAD

**Issue by sebvst** [aspnet-contrib/AspNet.Security.OAuth.Providers#117]
Hello,

I think the sandbox is not working if I pass the options object like this:

    app.UsePayPalAuthentication(new PayPalAuthenticationOptions 
    {
        ClientId = ConfigurationManager.AppSettings["PaypalClientId"],
        ClientSecret = ConfigurationManager.AppSettings["PaypalClientSecret"],
        IsSandbox = true
    });

I can login on the paypal page when I pass the single paramteres, but then my logininfo returns null. Is it maybe because I cannot pass the scope?

`               app.UsePayPalAuthentication(
                 ConfigurationManager.AppSettings["PaypalClientId"],
                ConfigurationManager.AppSettings["PaypalClientSecret"],
                true);`

Help on this one is highly appreciated.

**Comment by PinpointTownes** [comment]
Hey,

I suspect you're not using the Paypal provider developed for ASP.NET Core but the older version designed for OWIN/Katana (because the `IsSandbox` option doesn't exist in the vNext version).

I'd recommend opening a new ticket here: https://github.com/TerribleDev/OwinOAuthProviders

/cc @TerribleDev

**Comment by sebvst** [comment]
You are absolutely right! The issue can be closed here.
