### ISSUE TITLE
OAuth2 Provider for ADFS

### ISSUE THREAD

**Issue by SuperCreedy** [aspnet-contrib/AspNet.Security.OAuth.Providers#128]
I've created an OAuth2 Provider for ADFS adopting code from this repository and the following article: http://www.carbon60.com/blog/using-adfs-3-0-with-mvc-6-asp-net-5

Should I submit this as a pull request?

Cheers, James.

**Comment by PinpointTownes** [comment]
Sounds like a good idea (assuming your provider respects the structure we've adopted for all the other OAuth2 providers, of course) :+1:

**Comment by blowdart** [comment]
Oh no, I wouldn't. Support for confidential clients was [only added to ADFS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs). 

For previous versions you really need to be using WS-Fed.

**Comment by SuperCreedy** [comment]
There's some working code on my profile - but I agree this isn't needed any more as it was very specifically built as a workaround while WS-Fed middleware was unavailable for aspnet core.

**Comment by kevinchalet** [comment]
How would using WS-Federation make any difference? :confused: 

Unlike OAuth2 and OIDC, WS-Fed doesn't even make use of a backchannel call to retrieve the final token (i.e the token endpoint): the security token/assertion is directly returned to the RP, which is very similar to what you have with the implicit flow in the OAuth2/OIDC world.

The "only" downside with having a public client instead of a confidential one is that the access/identity tokens can be accessed by the resource owner (or any program running on his machine). When the app is a confidential client, this can't happen, as one must send the correct client credentials when redeeming the authorization code.

In the specific case of an ASP.NET Core app, this means the user could extract the authorization code from the authorization response and manually send the token request himself to get the access token. This is no big deal, and definitely not a good reason to justify using WS-Fed in 2018 :smile:

**Comment by blowdart** [comment]
You use old ADFS versions you use old protocols ;) Vittorio was very clear that oauth was a bad bad idea in older versions of ADFS

**Comment by SuperCreedy** [comment]
The code is here if anyone wanted to pick this up (I'd be glad the effort didn't go to waste!)

https://github.com/SuperCreedy/AspNet.Security.OAuth.Providers/tree/feature/adfs

Cheers, James

**Comment by kevinchalet** [comment]
> You use old ADFS versions you use old protocols ;)

I only use WS-Fed when I have absolutely no other option (just like OpenID 2.0, which a legacy protocol). OAuth2 is simpler and easier to implement. The threat model is also better and more recent (e.g it takes session fixation/XSRF attacks into account, countermeasures that the WS-Fed spec - and implementations like the Katana WS-Fed middleware - don't even mention or support natively).

> Vittorio was very clear that oauth was a bad bad idea in older versions of ADFS

Everything that has "AD" in its name is by definition a bad bad bad thing :trollface: 

@vibronet would you mind sharing some technical details about why it would be preferable to go with WS-Fed instead of plain OAuth2 on ADFS 3.0?

**Comment by kevinchalet** [comment]
@blowdart oh and JSYK: even in the marvelous ASP.NET Core world, the OIDC handler uses the implicit flow by default (`response_type=id_token`), which means the distinction between confidential and public clients is not even a thing (there's no backchannel call in implicit).

If you guys were so concerned about that, making implicit the default flow was not the right thing to do :laughing:
