### ISSUE TITLE
Fix for Vk provider

### ISSUE THREAD

**Issue by sla1k** [aspnet-contrib/AspNet.Security.OAuth.Providers#229]
Hello, I have fix for VK provider.

How can I contrib this fix?

**Comment by kinosang** [comment]
fork this repo, clone your fork to your local, commit your changes and push it back to GitHub, create a new pull request and wait for merging.

**Comment by sla1k** [comment]
@kinosang [PR #230](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/230)

**Comment by maxbl4** [comment]
Hi @sla1k , I also found this break with required version and did an adhoc fix in my code. The exception has gone, and it seems to work when I debug.
But login does not work. I login with VK in my sample asp.net core app. There are no errors but I'm still redirected back to login page.
The same happens when I take the code from your PR.
Can you help?

**Comment by maxbl4** [comment]
Ok, I found the issue. It seems, VK have also changed the field name for user id. It was uid, but now it is just id
This should be fixed in the latter PR, otherwise login will not work, it will not fill nameidentity claim

**Comment by sla1k** [comment]
@maxbl4 yes, you are right, I forgot include it to PR.

**Comment by sla1k** [comment]
@PinpointTownes  @maxbl4 add fix to PR

**Comment by kevinchalet** [comment]
Fixed.
