### ISSUE TITLE
Question: scopes per request

### ISSUE THREAD

**Issue by zAfLu** [aspnet-contrib/AspNet.Security.OAuth.Providers#258]
Hi,

is it possible to override scopes per request? If yes: how? :)

For example
```
Login request User "Admin": Add Scope "read_user" and "edit_user"
Login request User "RandomUser1": Only add Scope "read_user"
```

**Comment by Vertigo093i** [comment]
I suppose it is possible to add two different authentication schemes with different options for the same single provider.

```csharp
authBuilder.AddSomeProvider(...); // default with only 'read_user' scope
authBuilder.AddSomeProvider("SomeProvider-Admin", "SomeProvider for admin user", o =>
{
    o.CallbackPath = "/signin-someprovider-admin";
    o.Scope.Add("edit_user"); // assuming 'read_user' is already added by defaults for the provider
});
```

Then chose one depending on a user (application area) being authenticated.

**Comment by martincostello** [comment]
Looking at the code for OAuth handler, it looks like you can use the [`Scope` property](https://github.com/aspnet/AspNetCore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/Authentication/OAuth/src/OAuthChallengeProperties.cs#L23-L30) of the `OAuthChallengeProperties` class to amend the scopes used for a request.

https://github.com/aspnet/AspNetCore/blob/5502c2080e9c48e05effdb91695506cdbc14601a/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L241-L242

That's something core to the base implementation we build on top of though, so if it isn't possible it would be something that would need adding to ASP.NET Core itself, rather than here.
