### ISSUE TITLE
Add trakt.tv provider

### ISSUE THREAD

**Issue by TheUltimateC0der** [aspnet-contrib/AspNet.Security.OAuth.Providers#261]
I would like to add a provider for Trakt.tv

**Comment by PsiStorm69** [comment]
Hi, I am currently on leave and as I will be traveling, will have very limited access to email.  I will return on the 2nd of January 2019. 

Please contact the office at support@crowdedigloo.com or on 011-954-1949.

In an EMERGENCY, you can still contact me on my cellphone.

Regards
Storm Aki

**Comment by martincostello** [comment]
If you would like support for trak.tv to be added, please submit a PR.

**Comment by TheUltimateC0der** [comment]
There you go :)

**Comment by TheUltimateC0der** [comment]
When can I expect the NuGet package to be available on nuget.org ?

**Comment by martincostello** [comment]
The honest answer is...I don't know 😄 

I don't have permission to publish packages at the moment and we don't yet have any automation to do publishing either.

You can consume it from the MyGet feed though: https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Trakt

**Comment by TheUltimateC0der** [comment]
Would be great to have the package at nuget.org since I want to use it in an app. Who has permission to publish this package ?

**Comment by martincostello** [comment]
Is there a specific reason you can't just configure the MyGet feed feed in your `NuGet.config` file in your app repo and consume the package from there until there's a release of it in NuGet?

**Comment by TheUltimateC0der** [comment]
Cause every time there is a "quick and dirty" solution, it will be used for years. Cause it "just works" or there is "no need".

**Comment by martincostello** [comment]
Well like I said originally, I don't know when this would go into NuGet.org. The only person with access to upload packages to NuGet at the moment is @PinpointTownes.

If you're in a rush, you can use ProGet. Otherwise you'll have to wait until he has the time to help coordinate a release of a new 2.x version.

_At the latest_ this would go to NuGet.org in either September or early October once ASP.NET Core 3.0 ships and we release the 3.0 provider packages that support it.

**Comment by kevinchalet** [comment]
@TheUltimateC0der I'm not sure how referencing a MyGet feed can be seen as a "quick and dirty" solution since it's a very frequent approach.

You can't reasonably expect us to immediately release a new version on NuGet.org as soon as a provider is added ; otherwise we'd end up with tons of minor releases. Also, new providers first need to be tested in real apps so we can have enough feedback to determine whether they are working as intended prior to releasing it.

**Comment by martincostello** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/322#issuecomment-538507493

**Comment by TheUltimateC0der** [comment]
I added you (aspnet-contrib) as a co-owner. Please consider using proper CI-CD, so future changes will be available immediately on nuget.org after someone does the hard work of adding or changing something. I already mentioned this here https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/261#issuecomment-503168698

**Comment by TheUltimateC0der** [comment]
Is that how you treat contributors? I added you as a co-owner, and you deleted me from the NuGet package as a co-owner?

Re-add me as a co-owner!

**Comment by kevinchalet** [comment]
By contributing to this repository, you deliberately accepted that the `AspNet.Security.OAuth.Trakt` package be managed by the `aspnet-contrib` organization. It's a general and very frequent rule that helps guarantee that any package update is made by the appropriate org and not by someone or something else having write access.

**Comment by TheUltimateC0der** [comment]
Neither is it documented in the [contributing guidelines](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/.github/CONTRIBUTING.md), nor is it documented in your [code of conduct](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/CODE_OF_CONDUCT.md) or [README.md](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/README.md)

Asking me to make you a co-admin of something and then removing me as a co-admin is a dickmove in general.

How do we resolve this situation?

**Comment by kevinchalet** [comment]
> Asking me to make you a co-admin of something and then removing me as a co-admin is a dickmove in general.

I'm sorry you feel that way, but as I said, having full control of the packages we produce from this repository is essential for security reasons. We need to be sure only authorized changes are included in the packages pushed to NuGet.org.

> How do we resolve this situation?

I'm not sure I understand your motivation. If you want to make changes to the `AspNet.Security.OAuth.Trakt` package, feel free to send a PR and we'll make sure the package is updated as part of the next release.

**Comment by TheUltimateC0der** [comment]
> I'm sorry you feel that way, but as I said, having full control of the packages we produce from this repository is essential for security reasons. We need to be sure only authorized changes are included in the packages pushed to NuGet.org.

No, your are not sorry I feel that way, since this was intended from you when asking for making you a co-admin. So stop telling me lies.

Also who tells me that **YOU** dont add malicious code before you release a new version? _Security by obscurity_?

> I'm not sure I understand your motivation. If want to make changes to the `AspNet.Security.OAuth.Trakt` package, feel free to send a PR and we'll make sure the package is updated as part of the next release.

I have a problem with your release cycles/policy. You have no release automation, thus my changes can take months to get visible on nuget.org. This is not acceptable at all. There are tools for automating the complete process (building, testing, releasing, whatever else you do before uploading to nuget.org), and I cannot see any point why this project should be an exception to all other projects that do automated releases.

And since you wrote this
> You can't reasonably expect us to immediately release a new version on NuGet.org as soon as a provider is added ; otherwise we'd end up with tons of minor releases. Also, new providers first need to be tested in real apps so we can have enough feedback to determine whether they are working as intended prior to releasing it.

I guess this behavior will not change any time soon.


So either you re-add me as a co-admin of this project, or you delete my code, and remove the package from nuget.org

**Comment by kevinchalet** [comment]
> Also who tells me that YOU dont add malicious code before you release a new version? Security by obscurity?

It's all about trust. All the people who have write access to this repository are clearly identified by their real name and are well-known in the industry. We'd simply ruin our careers if we even tried to add malicious code to the packages we maintain. Correct me if I'm wrong, but that's not your case.

> I have a problem with your release cycles/policy. You have no release automation, thus my changes can take months to get visible on nuget.org. This is not acceptable at all. There are tools for automating the complete process (building, testing, releasing, whatever else you do before uploading to nuget.org), and I cannot see any point why this project should be an exception to all other projects that do automated releases.

The aspnet-contrib packages are automatically sent to MyGet.org when pushing changes against the default branch. Packages are only pushed to NuGet.org when we think it's time to release a new version. I can guarantee you this is a quite common approach (e.g when preparing a new release, the ASP.NET team builds final packages and stores them on internal feeds so they can be tested internally prior to releasing them).

If the change you want to introduce is important for you (e.g because it fixes a bug), we can certainly discuss shipping a hotfix in a short time frame.

> So either you re-add me as a co-admin of this project, or you delete my code, and remove the package from nuget.org

I'm sorry, I don't think it's going to happen.
