### ISSUE TITLE
Unable to build projects

### ISSUE THREAD

**Issue by tparnell8** [aspnet-contrib/AspNet.Security.OAuth.Providers#33]
I am unable to build the projects in this dir. Could there be a specific nuget package that the projects should be pinned to?

here is my error stack

```
Severity	Code	Description	Project	File	Line	Source
Error	CS1061	'GitHubAuthenticationOptions' does not contain a definition for 'Notifications' and no extension method 'Notifications' accepting a first argument of type 'GitHubAuthenticationOptions' could be found (are you missing a using directive or an assembly reference?)	AspNet.Security.OAuth.GitHub.DNX 4.5.1	C:\projects\AspNet.Security.OAuth.Providers\src\AspNet.Security.OAuth.GitHub\GitHubAuthenticationHandler.cs	45	IntelliSense


```

**Comment by tparnell8** [comment]
SO when I pin my project to 	"Microsoft.AspNet.Authentication.OAuth": "1.0.0-beta7", I am able to build.

**Comment by PinpointTownes** [comment]
Thanks for reporting it. This issue was caused by recent naming changes in aspnet/Security: https://github.com/aspnet/Security/pull/427

Though it was already on my radar, this is now fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/5f886c23dfa3543e503a4e290c5ee237d37d376e :tada:
