### ISSUE TITLE
Apple Code Exchange: Support flows based on native iOS AuthenticationServices

### ISSUE THREAD

**Issue by minichma** [aspnet-contrib/AspNet.Security.OAuth.Providers#399]
**Problem Statement**
When implementing Sign In With Apple on recent iOS devices, we use the [AuthenticationServices](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple) API to receive an ID token and an authorization code within the app. To authenticate a user with a web app, we need to send the credentials to the server and validate it there ([as outlined here](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple)).

This flow doesn't seem to be supported by `AspNet.Security.OAuth.Apple` at this time. To my understanding, only browser-based flows are supported today. If I'm wrong and it is supported, please treat this ticket as a question about how to implement this kind of flow.

**Describe the solution you'd like**
Support authentication flows based on credentials received by the native iOS `AuthenticationServices`, including periodic token re-validation.

**Describe alternatives you've considered**
* An alternative would be to use the `id_token` for authentication, using pre-existing technology that's not specific to _Sign In with Apple_ and not doing the `code` exchange altogether, but this would prevent doing re-validation at a later point in time.

**Comment by martincostello** [comment]
That's correct - we only support the web flows as that's in-keeping with the overall theme of these providers being to enable OAuth 2.0 login flows for ASP.NET Core web applications.

I'm not an iOS developer so have no experience of the native client-side scenarios for _Sign in with Apple_ in iOS.

Depending on the proposed solution, we might take a PR to add some infrastructure code to the provider, but it sounds like something that I would have thought would be some sort of separate project for dealing with exchanging tokens with client apps via an API, rather than part of this repo.

**Comment by minichma** [comment]
@martincostello 
> That's correct - we only support the web flows as that's in-keeping with the overall theme of these providers being to enable OAuth 2.0 login flows for ASP.NET Core web applications.

Thanks for the feedback. I understand. Is there any project you know of?

We're using IdentityServer and [I've created a ticket there, outlining the intended solution](https://github.com/IdentityServer/IdentityServer4/issues/4232). Basically we'd like to do some kind of custom token exchange that's usable from iOS apps and let the app use the returned access token and refresh token for accessing a separate resource server.

> Depending on the proposed solution, we might take a PR to add some infrastructure code to the provider

Which would be basic building block for building such a solution?

**Comment by martincostello** [comment]
Probably something that’s more a sort of library/interface sort of entry-point that fits in with the existing implementation that you could then call from your own controller/middleware/handler, rather than us having the URL and request handling stuff live here.

I’m just spitballing off the top of my head here, but I think we’d err away from having all the infrastructure for something like this living here as something you could just drop in and go like the normal OAuth identity stuff is.

**Comment by martincostello** [comment]
This isn't something we're planning to do so I'm going to close this.
