### ISSUE TITLE
The presence of a "System.Security.Claims.ClaimTypes.Email" claim is not present for the Apple provider.

### ISSUE THREAD

**Issue by lukefulliton** [aspnet-contrib/AspNet.Security.OAuth.Providers#407]
**Describe the bug**
There appears to be a bug in the Apple Provider.  Specifically the AppleAuthenticationHandler.cs file.  I noticed today, when debugging an app that utilizes the Apple provider, that the "System.Security.Claims.ClaimTypes.Email" claim was not present in the claims.  However, the claim of type "email" was present in the claims.  It looks like the method named "ExtractClaimsFromUser" is trying to add the "System.Security.Claims.ClaimTypes.Email" claim, however it appears to never be called.  I debugged the code and this is precisely what is happening.  There is a check for the existence of a "user" property in the parameters list, however there is no user property, therefore the "ExtractClaimsFromUser" method never gets called and the "System.Security.Claims.ClaimTypes.Email" claim is never added to the claims.  The app that I noticed this issue with utilizes the "authorization_code" flow, if that helps.  Also, the Apple user I was using to authenticate with did NOT hide the email.  I will submit a pull-request shortly with a proposed code change to resolve this issue.

**Steps To reproduce**
Authenticate via an authorization_code flow utilizing the Apple provider and do NOT choose to "Hide" your email.

**Expected behaviour**
The presence of a "System.Security.Claims.ClaimTypes.Email" claim should be in the list of claims.

**Actual behaviour**
The claim of type "email" was present in the claims.  

**System information:**
 - OS: [e.g. Windows 10]
 - Library Version [e.g. 2.2.0]
 - .NET version 2.0

**Comment by martincostello** [comment]
So I've just been playing with this using the sample integration I have (https://github.com/martincostello/SignInWithAppleSample), and I can't replicate this _based on my understanding_ of how Sign in with Apple works.

If I sign in for the _first_ time for a given application, then I get both the `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress` claim and the `email` claim, regardless of whether or not I hide my email address or not. I also do not receive the `email_verified` claim.

For each _subsequent_ I log in, I get neither claim. This is because Apple only share the user's email address (in both the JWT and the response) on the first sign in to the application by the user.

To test the behaviour multiple times, you need to go to `https://appleid.apple.com/manage/section/security/edit`, then find the _APPS & WEBSITES USING APPLE ID_ section, click _Manage..._, click your application, and then click the _Stop using Apple ID_ button.

Assuming this is correct, then neither PR would fix the issue as there'd never be an email claim to add, either from the JWT or identity.

I'm going to poke around further, but unless there's some configuration difference between our two application configurations that cause this behaviour, then this is _by design_ due to the restrictions from Apple on when the email address is shared.

**Comment by martincostello** [comment]
Screenshots from my testing:

## With Email Relay

![image](https://user-images.githubusercontent.com/1439341/79497070-0259c300-801f-11ea-9296-a58ab852725b.png)

## Without Email Relay

![image](https://user-images.githubusercontent.com/1439341/79497192-2f0dda80-801f-11ea-9184-66313fd4fa8d.png)

## Second Sign In

![image](https://user-images.githubusercontent.com/1439341/79497271-4baa1280-801f-11ea-91e4-c087c70533d8.png)

**Comment by lukefulliton** [comment]
@martincostello Thanks for looking into this.  I will review your findings in more detail later, however, I was curious to know what OAuth grant types were you testing with?  Please try a test ONLY using the "Authorization Code" grant type if you have not already done so.  Thanks again for troubleshooting this.

**Comment by martincostello** [comment]
The short answer regarding "Authorization Code" is...I don't know 😄 

The sample app is configured using pretty much all the defaults of this provider and ASP.NET Core for identity. If you take a look at the sample app and compare it to your app, you might be able to work out which it is: https://github.com/martincostello/SignInWithAppleSample

If it's not "Authorization Code" I can try reconfiguring the sample app to use it and try debugging again tomorrow.

**Comment by kevinchalet** [comment]
The authorization code flow is the only grant type supported by the OAuth 2.0 generic handler, so you’re already using the only possible configuration.

**Comment by martincostello** [comment]
Thanks @kevinchalet.

In that case, as it stands I can't replicate this as I either get both claims, or neither.

**Comment by lukefulliton** [comment]
I think you may be right @martincostello , it sounds like a configuration difference or some kind of environmental difference.  I will spend some more time this weekend reviewing this to see if I am able to identify the differences.  Off the top of my head, I know one difference may be that my environment is utilizing IdentityServer4, but I am not sure if that would be causing the discrepancy in app behavior.  I guess whatever the underlying cause, every time I authenticate via the Apple provider, which has been countless times with the same Apple user, the ID Token always has the "email" claim and the correct corresponding email value.  In my environment I have never seen it missing from the ID Token.

**Comment by lukefulliton** [comment]
Out of curiosity @martincostello , were you required to input your username and password everytime your test app tried to utilize Apple for authentication?  Did you have to logout in between consecutive tests?

**Comment by martincostello** [comment]
Yes, I was logging out of the sample app, and then Apple would require me to enter my password , then click a button to confirm on the next page before the flow went back to the sample app. That was on Chrome of Windows.

However, I just logged in using Chrome on my iPhone where instead of credentials I just need to confirm sign in with Face ID, it _does_ have the `email` claim, but not the other.

My guess here is that the native iPhone flow is “trusted more” than Windows or is enhanced by the iOS device itself, and then always returns the extra claim.

With that to go on, I’ll have a further investigation later today using my phone to log in, rather than the desktop I’m using for debugging.

**Comment by martincostello** [comment]
I've opened #411 as a candidate fix. Assuming other people agree, I'd prefer this over #408 or #409 as it doesn't change the public surface area of the library by adding new members and doesn't require the ID token to be parsed twice.

A version of the sample site with the fix is deployed here if you'd like to try it out: https://signinwithapple.azurewebsites.net/

From playing around with signing in with Chrome on both my Windows 10 laptop and on my iPhone with Face ID, it seems that there's _something_ going on (at least without the suggested fix) that means that the email was getting "lost" with the Chrome Desktop login I was doing, and I'd only get the email on the iPhone.

With the fix, I seem to get both email claims in both scenarios now all the time. It's almost as if the fix, coupled with some sort of server-side heuristic, was altering the server behaviour on Apple's side. It's just the first and last names now that only come through on the first sign-in.

**Comment by lukefulliton** [comment]
BINGO @martincostello !  Thank you so much for all your troubleshooting work!  This has been a very weird and perplexing issue.  I think your candidate https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/411 is the best path forward.

**Comment by lukefulliton** [comment]
@martincostello would it be helpful if I submitted a pull-request with your solution implemented in the .NET Core 2 rel branch?  I know [alaincroisetiere](https://github.com/alaincroisetiere) had mentioned releasing the fix in a 2.x version would be helpful.

**Comment by martincostello** [comment]
> BINGO @martincostello ! Thank you so much for all your troubleshooting work! This has been a very weird and perplexing issue. I think your candidate #411 is the best path forward.

Great, I'll merge that shortly then.

> @martincostello would it be helpful if I submitted a pull-request with your solution implemented in the .NET Core 2 branch?

Sure - if you checkout the `rel/2.2.1` branch locally, then we can merge the fix for 2.2 into that branch directly from the PR.

**Comment by lukefulliton** [comment]
> Sure - if you checkout the `rel/2.2.1` branch locally, then we can merge the fix for 2.2 into that branch directly from the PR.

Great, the PR is submitted here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/412.

**Comment by martincostello** [comment]
Two releases containing this fix are now available on NuGet.org:
  * [2.2.1](https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/2.2.1)
  * [3.1.0](https://www.nuget.org/packages/AspNet.Security.OAuth.Apple/3.1.0)

**Comment by alaincroisetiere** [comment]
@martincostello & @lukefulliton thank you!
