### ISSUE TITLE
Question: Discord Persistence

### ISSUE THREAD

**Issue by imukai** [aspnet-contrib/AspNet.Security.OAuth.Providers#428]
### Provider name

AspNet.Security.OAuth.Discord  v3.1.1

### Expected (desired?) behavior

Persisted permission.

### Actual behavior

Permission does not persist.

### Steps to reproduce

Log in, Log out, Log in again.

### Additional information

I've used Facebook and Google successfully as login providers for a few years.  A couple of weeks ago I upgraded my project to core 3.1 and had to move Google to OpenIdConnect as recommended by MS.

Today I tried plugging in Discord at the request of some users.

It seems to work fine - with the exception that **every time** the user clicks the Discord button on the login page, Discord's page asks for permission, even after they have granted it.

Google and Facebook do not ask for permission every time - after the user grants permission once, future logins go right through and redirect back to my site.  

So I am wondering if I don't have something flagged correctly in the configuration.  I started with just the ClientId and ClientSecret then tried specifically adding the "identity" scope, and then the "email" scope.  I've also turned `SaveTokens = true` after doing some reading.

Now I'm at a loss -- is this expected behavior to pester the user for permission every time they want to log in to my site with Discord?

Thank you.

**Comment by kevinchalet** [comment]
It's the expected behavior: it's up to the authorization server to decide whether it asks for user consent once or every time it receives an authorization request. For reasons I ignore, Discord has opted for the second approach.

The good news is that Discord allows you to override this behavior using `prompt=none` (except when requesting sensitive scopes like `bots`), so it's something we'll be able to easily add: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/415

The bad news is that the `prompt` parameter is also an OIDC parameter, that has a different behavior for `none`: if the user is not authenticated or hasn't previously authorized the application, then the server MUST return an error, instead of offering a way to login/consent. If they ever decide to implement OIDC, things will likely stop working properly... 😢

**Comment by imukai** [comment]
Is this something I can hack in and deal with repercussions later if they decide to implment OIDC?  Or do you need to make a change in the code to allow the option?

Really I'm more concerned right now with annoying users - as I would be if Google constantly asked me to approve an action.

**Comment by martincostello** [comment]
> Is this something I can hack in and deal with repercussions later if they decide to implment OIDC? Or do you need to make a change in the code to allow the option?

First try using the latest version of the 3.1.2 provider from our MyGet feed. It includes the change to support the use of the `prompt` parameter as-per #415.

If that doesn't work and you want to hack about with it to work around it, then your best option is to fork the repo and make some changes and consume that version with whatever customisations you need, rather than ours.

Anything considered a "hack" wouldn't be accepted for merging to the provider we ship.

**Comment by imukai** [comment]
I grabbed the 3.1.2 nightly build from MyGet and added Prompt = "none" to the startup options.

A discord page does appear for about 3/4 of a second but it quickly redirects back to my site.  Good stuff.

I didn't know this was in the pipe to get added already -- from Kevin's comment above it seemed like something you'd be considering, so I was just following up on that.  :)  I'll keep an eye out for 3.1.2 proper.

**Comment by martincostello** [comment]
Resolved by #415.

**Comment by martincostello** [comment]
The final release of the 3.1.2 package is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Discord/
