### ISSUE TITLE
Update to Patreon v2 API

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#433]
As raised in #432, Patreon now has a [v2 API in beta](https://docs.patreon.com/#what-39-s-new).

Once it is stable, we should update the Patreon provider to use the new v2 API.

**Comment by AraHaan** [comment]
If anyone needs help I figured out a few other things related to their api including tier information, patron names, if former, current, or denied patrons, etc. If you need I can provide a copy of that code (although it might be a little all over the place and uses timers to automatically regenerate any access tokens right at 12 AM on the first of every month so ye. I did this to prevent them expiring before refreshing them.

**Comment by AraHaan** [comment]
Oh and technically the v2 api is stable they just have not updated the docs after a few years is all. I actually know someone who actually built their api however they no longer work for them and he said that v2 is more stable than v1 atm and also said it is ideal to move everything to v2 api atm since it will be easier to do all sorts of things. I will also look into things on the v2 api like getting the user’s memberships for specific people and their tiers as well (if the claims stuff on the oauth provider on this package does not provide that information yet at all). It would help a ton for people like me.

**Comment by martincostello** [comment]
The update for the v2 API will be available as part of our 3.1.2 release.

Until then, you can consume the changes from our MyGet feed starting with version [3.1.2-preview.20353.75](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Patreon/3.1.2-preview.20353.75).

**Comment by martincostello** [comment]
Version 3.1.2 of the Patreon provider that uses the v2 API is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Patreon/
