### ISSUE TITLE
Getting {"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"} while using Instagram 

### ISSUE THREAD

**Issue by ar-reddy** [aspnet-contrib/AspNet.Security.OAuth.Providers#435]
Hi Team,

I am using the Latest "AspNet.Security.OAuth.Providers" Instagram 

I am getting below error 

{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"}

Can u please help to resolve 

Thanks
Koni

**Comment by martincostello** [comment]
The `"basic"` scope comes from here:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/02e50174cc7cd418c3653152ada6de640fad9fe3/src/AspNet.Security.OAuth.Instagram/InstagramAuthenticationOptions.cs#L28

Have Instagram changed their API that makes this default no longer valid?

**Comment by ar-reddy** [comment]
@martincostello 
I added But still getting the same issue

Please check below image 

![image](https://user-images.githubusercontent.com/56219917/85311543-38aa3780-b4d3-11ea-9b36-30dd95200636.png)

**Comment by martincostello** [comment]
You don’t need to add it, it’s already configured for you by the provider, that’s what the line of code I linked to does.

You’ll need to call the `Clear()` method to remove it and consult the Instagram API documentation to find what scope(s) should be being used instead.

**Comment by mateolevy** [comment]
@martincostello Instagram deprecated their legacy API.

> UPDATE
The remaining Instagram Legacy API permission ("Basic Permission") was disabled on June 29, 2020. As of June 29, third-party apps no longer have access to the Legacy API. To avoid disruption of service to your app and business, developers previously using the Legacy API should instead rely on Instagram Basic Display API and Instagram Graph API. Please request approval for required permissions through the App Review process.

The scopes to use are different now. Basic is no longer working since the API is deprecated.

**Comment by mateolevy** [comment]
For more information: https://www.instagram.com/developer/

**Comment by martincostello** [comment]
Thanks for the update @mateolevy - I'll create a separate issue to track us needing to update the Instagram provider to use the new APIs.

**Comment by martincostello** [comment]
I'm going to close this in favour of #441 - thanks again for bringing this to our attention @mateolevy 🍪
