### ISSUE TITLE
Which version of .NET should dev target?

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OAuth.Providers#502]
Now that the ASP.NET 5.0 version of the providers has shipped to NuGet.org, how do we want to manage the branches/versions?

As of the time of writing we have `dev` targeting .NET Core 3.1 LTS, plus the branch for 5.0 that branched off from an earlier 3.1 release.

## Potential Options

  1. Merge `rel/5.0.0` to `dev` and move forward only supporting 5.0 until 6.0 is released.
  1. Branch `dev` to a `rel/3.1.x` (or other name) branch and then merge `rel/5.0.0` to `dev`. We then release for both 3.1 and 5.0 from branches from `dev` and `rel/3.1.x` as appropriate and ensure changes are ported to both branches as appropriate.
  1. As above, except with 3.1 for `dev` and 5.0 on its own `rel/5.0.x` (or similar name) branch.
  1. Other?

Whatever we decide I guess we should use as the approach going forward for support when the latest release is non-LTS, like when 7.0 comes out alongside 6.0 being supported.

Same question applies to the OpenID repo.

**Comment by kevinchalet** [comment]
Tough question 😅 

Other potential options:
  1. We could decide to multi-target the latest TLS + the latest current version (e.g 5.0 could target `netcoreapp3.1` and `net5.0`, 6.0 would be `net6.0` only). I was not a huge fan of this option in the past - mostly because the changes introduced in the OAuth 2.0 generic provider in 3.0 made that quite impractica (the API should is now rather stable, which should make multi-targeting much less painful).

  2. As you suggested in 1), we could merge `rel/5.0.0` into `dev` and backport select bug fixes to 3.0 by using Git tags to create a `rel/3.0.x` branch when needed (no need to keep it around if we don't need it).

**Comment by martincostello** [comment]
With 5.0 I took the opportunity to use the new one-shot hash methods in some places, plus there were breaking changes to the Apple provider to rework the DI setup, so reworking it to multi-target now would be a bit of a faff.

Out of the two options above I'd go with option 2, but we could take the aim in the future for 6.0 and forwards of approaching it via multi-targeting when making the changes.

**Comment by martincostello** [comment]
Any strong preference on the options to go with? I'd like to implement whatever the decision is before merging #507.

**Comment by kevinchalet** [comment]
I'd go with 2) too (not really a "strong opnion, tho') 😄

**Comment by martincostello** [comment]
Cool, thanks, I'll get that sorted out in the next few days then 👍🏻

**Comment by LeaFrock** [comment]
I'd go with 2) too.
I advice `dev` to represent the latest version (for both codes and SDK).
`rel/3.1.x` is good for now. And when .NET 6 releases, the `dev` should checkout `rel/5.x`（since there won't be .NET 5.1）then keep moving on for upgrading to .NET 6.
It's a balance between compatibility and workload.

**Comment by martincostello** [comment]
I plan within the next week or so to (assuming PRs are all good to go soon):

  1. ~Merge #507~
  3. ~Merge #511~
  4. ~Create a `rel/3.1.7` branch~
  5. ~Branch from `rel/5.0.0` to incorporate latest changes, then merge that to `dev`~
  6. ~Create a `rel/5.0.1` branch~

End state should be 3.1.7 and 5.0.1 releases, and the `dev` branch targeting .NET 5.0. After that I guess we'd just continue on with new providers with 5+ and not look at any more 3.1.x releases unless there's a good reason.

**Comment by martincostello** [comment]
Awaiting a response to this comment before starting steps 3-5 above: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/507#issuecomment-770405632

**Comment by martincostello** [comment]
All sorted - just need to do the "stabilise versions" changes to the two release branches.

Will look at releasing the 3.1.7 and 5.0.1 versions to NuGet tomorrow.

**Comment by martincostello** [comment]
[3.1.7](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/releases/tag/3.1.7) and [5.0.1](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/releases/tag/5.0.1) have been published to NuGet.org.
