### ISSUE TITLE
Discord Cancel throws exception on callback

### ISSUE THREAD

**Issue by pnmcosta** [aspnet-contrib/AspNet.Security.OAuth.Providers#506]
**Describe the bug**
With the Discord provider v3.1.6, if a user cancels the authorize login the callback throws a "Access was denied by the resource owner or by the remote server." exception.

**Steps To reproduce**
With IDS4 (v3) add Discord, attempt to login but cancel without authorizing on Discord prompt.

**Expected behaviour**
Should cancel the login flow and redirect to the return url if provided? Not sure really.

**Actual behaviour**
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

![image](https://user-images.githubusercontent.com/550684/103928080-3b891480-5113-11eb-992b-3c8359082134.png)

**System information:**
 - OS: Windows Dev
 - Library Version: 3.1.6
 - .NET version: netcoreapp3.1

**Additional context**
Original Angular SPA template (netcoreapp3.1) with IDS authentication

**Comment by martincostello** [comment]
You have to explicitly handle access denied by either setting the [`AccessDeniedPath`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.remoteauthenticationoptions.accessdeniedpath?view=aspnetcore-3.1) property to an appropriate path to redirect the user to, or handle the event via the [`OnAccessDenied`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.remoteauthenticationevents.onaccessdenied?view=aspnetcore-3.1) event handler to tell your app what to do in that eventuality, otherwise you get the default behaviour you're observing, which is for an exception to be thrown.

You can see the way the logic is implemented in the base class for the Discord provider [here](https://github.com/dotnet/aspnetcore/blob/e3187077455f953200e3c930430808a30f48b82e/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L66-L89) and [here](https://github.com/dotnet/aspnetcore/blob/e3187077455f953200e3c930430808a30f48b82e/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L246-L287).

Looking at your screenshot, the return URL includes `error=access_denied`, so it should flow through the code paths above.

To get a different behaviour, you need to either set the access denied path or implement the appropriate logic for what you want to happen in the event. For example:

```csharp
options.AccessDeniedPath = "/access-was-denied";

options.Events.OnAccessDenied = context =>
{
    // TODO Do something custom to handle it
    context.HandleResponse();

    return Task.CompletedTask;
};
```

**Comment by pnmcosta** [comment]
got it, thanks so much @martincostello I missed this on the documentation.
