### ISSUE TITLE
State too long for twitch

### ISSUE THREAD

**Issue by DTX-Liam** [aspnet-contrib/AspNet.Security.OAuth.Providers#577]
**Describe the bug**
The state parameter in the url query is too long when requesting a lot of scopes on twitch.

**Steps To reproduce**
Use the twitch provider with almost all possible scopes and the url string is too long, twitch will return 500 invalid authorization.

**Expected behaviour**
The authorization should be performed by twitch and the state returned correctly, this works fine when manually changing the state to be a UUID as recommended by the twitch docs.

**Actual behaviour**
Twitch returns a 500 internal server error with the message "invalid authorization", this does not happen with a shorter state.

**Comment by martincostello** [comment]
If Twitch is returning an HTTP 500, then that sounds like a bug on their end. If the request was invalid, they should return an HTTP 400.

That's not to say this shouldn't/couldn't also be changed in the provider, but HTTP 500 maps to Internal Server Error, which implies an issue on their end.

**Comment by DTX-Liam** [comment]
Yes its a bug on their end that its returning 500 not 400 however the state sent to twitch should be shorter or just set to a UUID for the twitch provider as is the example in their docs.

**Comment by kevinchalet** [comment]
States are generated by the MSFT OAuth 2.0 base handler (it's basically an encrypted representation of `AuthenticationProperties` to which a random value was added): it's not something we control on our side.

**Comment by martincostello** [comment]
Yeah, the state is [read here](https://github.com/dotnet/aspnetcore/blob/e65cec17d41f5563f2c5dde35422741f11e3fabb/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L63-L69) and [generated here](https://github.com/dotnet/aspnetcore/blob/e65cec17d41f5563f2c5dde35422741f11e3fabb/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L321).

To use a different state transfer mechanism, the Twitch provider would need to re-implement `BuildChallengeUrl()` and `HandleRemoteAuthenticateAsync()` to flow the state in a way that would make it stateful rather than stateless (because the GUID would need to be a reference back to something the app already had access to).

You could either subclass the `TwitchProvider` yourself to extend it in your own code (I don't think we'd want the additional complexity back in the provider for us to maintain), or maybe you could change your implementation to ask for less scopes initially, and then request further scopes from the user at a later stage?

**Comment by DTX-Liam** [comment]
Thanks for the insight, I appreciate you guys taking the time to help, I'm going to try to find a workaround.

I understand you dont want additional complexity to maintain thats provider specific but as twitch continually update their API's they are adding more and more scopes so this is going to continue to be a problem for more users in the future. A url string of over 2000 characters is a bit excessive.

**Comment by martincostello** [comment]
It might be worth opening an issue against the ASP.NET Core repo for the _general_ use case, with Twitch as a _specific_ example, of scenarios where the state is too wrong and the best way to make that easier to deal with for any arbitrary OAuth provider if `state` is too long.

The advantage of the current approach with everything carried in the callback URL is that it works in web farms so multiple instances don't need to synchronise to a common shared data store in the case where you were using a UUID string to reference back to state in the consuming application.

Maybe there's a possibility of API changes to make it easier to change the state implementation. So you could plug in your own way to do the Twitch recommended way without having to reimplement both of those methods.

Alternatively, I haven't looked into it, it might be the case that you _can_ already do that today by providing a custom implementation of the DataProtector to change the implementation there so that the Protect and Unprotect methods do what's been mentioned above.

I'm writing this on my phone, and now I've written the second suggestion I think that's actually the better thing to do first, but I don't want to try and re-format this all again now 😆

See if you can customise the data protector on the options to use the UUID approach Twitch recommend, and failing that _then_ ask for guidance in the AspNetCore repo.

If the DataProtector change approach worth, then we'd gladly accept a PR to the documentation for our Twitch provider showing how to solve the problem.

**Comment by martincostello** [comment]
Closing as external, as the best overall approach is to have the ASP.NET Core base implementation we build on top of have appropriate extensibility/features to handle this scenario generically for all OAuth providers.
