### ISSUE TITLE
Discord OAuth provider returns .png avatar url for animated avatars

### ISSUE THREAD

**Issue by ndelta0** [aspnet-contrib/AspNet.Security.OAuth.Providers#584]
**Describe the bug**
Claim for Discord Avatar Url always has an extension of `.png` even if the avatar is animated.

**Steps To reproduce**
n/a

**Expected behaviour**
Claim for avatar url ends in `.gif` for animated avatars/

**Actual behaviour**
Claim always ends with `.png`

**System information:**
 - OS: n/a
 - Library version 5.0.9
 - .NET version: n/a

**Additional context**
As per [Discord Documentation](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints) users that have an animated avatar have a avatar hash that always starts with `a_`.

**Comment by martincostello** [comment]
The _"best"_ way to fix this would be in version 6 as it requires a change to a constant, which is a breaking change.

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/f9059d3f80ddd4158b298820a0008329545ee45c/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationConstants.cs#L17

For earlier versions you can work around this by either:

1. Changing the format string used to create the avatar claim: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/f9059d3f80ddd4158b298820a0008329545ee45c/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs#L25-L30
2. Adding your own custom claims action that does what you would like it to do: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/f9059d3f80ddd4158b298820a0008329545ee45c/src/AspNet.Security.OAuth.Discord/DiscordAuthenticationOptions.cs#L55-L61

**Comment by martincostello** [comment]
Rather than try and maintain the code to do this and keep in sync with Discord, we've removed this functionality from the v6 release and won't be fixing this in the v5 provider.

Here is a snippet from the updated provider documentation for v6 that shows how to configure this for users who want/need the claim.

---

## Avatars as Claims

Versions of the Discord provider before version `6.0.0` would automatically map the user's avatar URL as the `urn:discord:avatar:url` claim.

This functionality is no longer built-in (see [#584](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/584) and [#585](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/585)), but can be added to your application with some extra code similar to that shown in the sample below.

```csharp
services.AddAuthentication(options => /* Auth configuration */)
        .AddDiscord(options =>
        {
            options.ClientId = "my-client-id";
            options.ClientSecret = "my-client-secret";

            options.ClaimActions.MapCustomJson("urn:discord:avatar:url", user =>
                string.Format(
                    CultureInfo.InvariantCulture,
                    "https://cdn.discordapp.com/avatars/{0}/{1}.{2}",
                    user.GetString("id"),
                    user.GetString("avatar"),
                    user.GetString("avatar").StartsWith("a_") ? "gif" : "png"));
        });
```
