### ISSUE TITLE
Old iPhone 6s / Mobile Version

### ISSUE THREAD

**Issue by kennethlou** [aspnet-contrib/AspNet.Security.OAuth.Providers#637]
Hi,

I just downloaded the sample project. I compiled and deployed it onto my VPS. There is an SSL certificate installed.

When I tried it in chrome on desktop, it works very well. However, I tried it on my old iPhone 6s browser and I can see only a white blank page after login. Do you know how to see the error message, given that I can only see a white blank page in the old iPhone. 

I know it works on the new iPhone 13, but I am trying to at least display an error message to the user.

Regards,

**Comment by martincostello** [comment]
Something for you to check in the debug logs server-side?

My guess might be something related to [SameSite cookies](https://devblogs.microsoft.com/dotnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/) if it's an older phone using Safari.

Otherwise my only suggestion is to test it with developer error pages turned on and/or a custom error page to see if you shed more light on the issue with your app client-side.
