### ISSUE TITLE
Could support for .NETCore3.1 be added to some newer connectors?

### ISSUE THREAD

**Issue by Luk164** [aspnet-contrib/AspNet.Security.OAuth.Providers#661]
**Is your feature request related to a problem? Please describe.**
I recently needed a Keycloak connector for a .NetCore3.1 project and found out only 5.0+ is supported. I forked and modified it to support 3.1 and it worked without much trouble and I do not see why it could not target even .NetStandard.

**Describe the solution you'd like**
Adding .NetCore3.1 or NetStandard targets to all modules that could support them.

**Describe alternatives you've considered**
Nothing comes to mind.

**Comment by martincostello** [comment]
Unfortunately the packages cannot target .NET Standard as they depend on a component of ASP.NET Core itself (`Microsoft.AspNetCore.Authentication.OAuth`) which is only available in the shared framework (`Microsoft.AspNetCore.App`) and not from NuGet since ASP.NET Core 3.0.

We haven't previously backported new changes to previous versions because there wasn't any demand (until now) and because it's a non-trivial amount of additional work to manage to maintain what is now over 70 OAuth providers for more than one version of ASP.NET Core.

At this stage with .NET Core 3.1 going [out of support in 8 months](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), I don't think it would be a good investment of time and effort to resurrect the 3.1 branch which has been dormant for quite some time just for a few months of usage before support ends. The codebase already uses various newer APIs that do not exist in ASP.NET Core 3.1, so it isn't as simple as just multi-targeting.

This is something we could _consider_ for LTS versions going forward with .NET 6+ when .NET 7 arrives in, but I think for this specific request you're best using your own fork for Keycloak support.

**Comment by Luk164** [comment]
@martincostello Oh well, at least I tried. The project I am working on is stuck on 3.1 for the foreseeable future. While the base website could be updated all the way to .NET6, the plugins we rely on are another matter entirely. Would there be any objection if I created my own nuget package for that one specific module? I will of course credit this repo.

**Comment by martincostello** [comment]
No objections from me!

**Comment by Luk164** [comment]
Here is the resulting package, should anyone ever need it. https://www.nuget.org/packages/Luk164.AspNet.Authorization.KeyCloak/

**Comment by kevinchalet** [comment]
FWIW, the MSFT OIDC handler is probably a better choice for KeyCloak integration: KeyCloak fully supports OpenID Connect and the OIDC handler will benefit from that by enforcing more security checks than what the OAuth 2.0 base handler and the KeyCloak provider from this repo support (e.g there's no `id_token` validation at all in the KeyCloak provider).

**Comment by Luk164** [comment]
@kevinchalet Do you by any chance have an example for what an OIDC configuration would look like for keycloak?

**Comment by kevinchalet** [comment]
https://github.com/tuxiem/AspNetCore-keycloak should put you on the right track 😃
