### ISSUE TITLE
Authentiation error with Apple in Production environment

### ISSUE THREAD

**Issue by ToniGallego87** [aspnet-contrib/AspNet.Security.OAuth.Providers#699]
### Provider name

Apple

### Expected behavior

We have problems when we doing the OAuth authentication with the Apple provider. It´s working in Develop environment, but when we try in Production one it´s not work. We have the same configuration for both environments, and the code is exactly the same too. The only difference is the Azure AppService, and the database.

### Actual behavior

This is the error we have in Production:

_2022-07-22 10:12:42.833 +00:00 [INF] Error from RemoteAuthentication: The oauth state was missing or invalid.. <correlationId:4364c38f-0f5b-4c96-adb0-76bdcd578045>
2022-07-22 10:12:42.838 +00:00 [ERR] Connection ID "13330654902922248466", Request ID "80000115-0001-b900-b63f-84710c7967bb": An unhandled exception was thrown by the application. <correlationId:>
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: The oauth state was missing or invalid.
   --- End of inner exception stack trace ---_

Can anyone help us? :(

**Comment by martincostello** [comment]
I'm not sure it would work correctly with _exactly_ the same configuration in two different environments because the domain names for the websites would be different.

The error seems to suggest that the Apple servers aren't returning the `state` parameter back to you in the callback URL after authentication completes.

**Comment by ToniGallego87** [comment]
Hi Martin! Thank you for the answer. Apple lets you configure a set of allowed urls for the callback, so in our configuration we have the urls for both pre-production and production environments.

Apple is returning to us a state, but do you think is it possible that this state is for the pre-production domain even though we have made the request from production?

**Comment by martincostello** [comment]
Looking at the code for the OAuth handler in the ASP.NET Core repo, the exception comes [from here](https://github.com/dotnet/aspnetcore/blob/307918d33b2ce5accbc7aa0659440dca44617d3f/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L59-L65).

If there definitely is a `state` parameter being passed back, then maybe the unprotect operation is failing.

Do you have appropriately different cookie and data protection settings between your development and production environments? Are those appropriately configured for [use in a load-balanced configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-6.0#data-protection)? 

Could it be that in development you have one server but in production you have many, and requests served by one server cannot be read by another because they have different data protection keys?

**Comment by ToniGallego87** [comment]
The state parameter definitely is being passed back, so it has to be a problem with the unprotect operation.

As you have deduced, there is only one server in development, and there are more than one in production (2 min, 12 max, depending on the current proccess). The configuration of the data protection was this:

`.PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, @"persistkeys\")))`

I don´t know if this can be a problem, but I have changed to this:

`.PersistKeysToAzureBlobStorage(container, "test")`

...and I have the same result (I have checked that 'test' file was perfectly created in the proccess). The provider configuration is like this:

```
authenticationBuilder.AddApple
                (
                    AuthenticationSchemeFor("Apple", clientName),
                    options =>
                    {
                        Apple externalLoginInfo = externalLoginsConfig.Apple[clientName];
                        options.ClientId = externalLoginInfo.ClientId;
                        options.TeamId = externalLoginInfo.Iss;
                        options.KeyId = externalLoginInfo.KeyId;
                        options.SaveTokens = true;
                        options.ClientSecret = GenerateAppleClientSecret(externalLoginInfo.ClientId, externalLoginInfo.Iss, externalLoginInfo.Auditory, externalLoginInfo.KeyId, externalLoginInfo.PrivateKey);
                        options.CallbackPath = "/signin-apple/" + externalLoginInfo.ConfigurationId;

                        options.Scope.Clear();
                        options.Scope.Add("openid");
                        options.Scope.Add("email");
                        options.Scope.Add("name");
                    }
                );
```

And this is the code of the for the GenerateAppleClientSecret method:

```
private static string GenerateAppleClientSecret(string sub, string iss, string aud, string kid, string privateKey)
        {
            double iat = Math.Round((DateTime.UtcNow.AddMinutes(-1) - new DateTime(1970, 1, 1, 0, 0, 0)).TotalSeconds, 0);

            // The value must not be greater than 15777000 (6 months in seconds) from the Current UNIX Time on the server
            // https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens
            double exp = Math.Round((DateTime.UtcNow.AddSeconds(15777000) - new DateTime(1970, 1, 1, 0, 0, 0)).TotalSeconds, 0);

            var payload = new Dictionary<string, object>()
            {
                { "sub", sub },
                { "exp", exp },
                { "iat", iat },
                { "iss", iss },
                { "aud", aud },
            };

            var extraHeader = new Dictionary<string, object>()
            {
                { "alg", JwsAlgorithm.ES256.ToString() },
                { "typ", "JWT" },
                { "kid", kid }
            };

            var keyString = privateKey;

            System.Security.Cryptography.CngKey cngPk = System.Security.Cryptography.CngKey.Import(Convert.FromBase64String(keyString), System.Security.Cryptography.CngKeyBlobFormat.Pkcs8PrivateBlob);

            string token = JWT.Encode(payload, cngPk, JwsAlgorithm.ES256, extraHeader);

            return token;
        }
```

Any idea? :(

**Comment by martincostello** [comment]
What does your blob storage code for the keys look like? Persisting keys to the file system would definitely be incorrect for a load balanced fleet (and for cloud in general as if the cloud provider swapped out the instance for maintenance you’d lose the keys).

Is there a reason you’re re-implementing the secret generation when it’s already built-in to the provider?

**Comment by ToniGallego87** [comment]
This is the complete blob storage code:

```
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(connectionString);
CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
CloudBlobContainer container = blobClient.GetContainerReference("test_container");

services.ConfigureApplicationCookie
                (
                    config =>
                    {
                        config.Cookie = new CookieBuilder
                        {
                            Name = GetCookieName(),
                            SameSite = SameSiteMode.None
                        };
                        config.LoginPath = new PathString("/Login/LoginRedirect");
                        config.AccessDeniedPath = new PathString("/Login/LoginRedirect");
                        config.SlidingExpiration = true;
                    }
                )
         .AddDataProtection()
         .PersistKeysToAzureBlobStorage(container, "test")
         //.PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, @"persistkeys\")))
         ;
```

I don´t know the reason why this code is re-implementing the secret generation, because this part of the code was already implemented when I arrived, but I have total freedom to change it. Do you think I should remove this part?

**Comment by martincostello** [comment]
The code _seems_ fine (although I'm not 100% sure on the `SameSite` setting). The only other thing I can think of for data protection is setting an explicit application name to remove another _possible_ source of variation ([`SetApplicationName(string)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionbuilderextensions.setapplicationname)).

Unless it doesn't work for your use case, I would recommend removing the custom code (there's already refactor opportunities in it like using `DateTimeOffset.UnixEpoch` instead of manually creating the date in 1970) and using the built-in secret generation code which is production-proven, as that removes another possible variable from why your setup isn't working.

My sample project has an [example](https://github.com/martincostello/SignInWithAppleSample/blob/58c464e4814138d6e7e07b37d652c58b9a20877f/src/SignInWithApple/AuthenticationModule.cs#L37-L53) of configuring the private key generation for a `.p8` file on disk and Azure Key Vault, and the [implementation for Key Vault](https://github.com/martincostello/SignInWithAppleSample/blob/0ff1267340417f7747a2f715c83872a89d5282bd/src/SignInWithApple/AppleAuthenticationOptionsExtensions.cs#L31-L35) shows how to use an arbitrary secret string containing the key if you just have it stored as an environment variable or similar.

**Comment by ToniGallego87** [comment]
I've tried your SetApplicationName(string) suggestion, but it didn't work:

```
.AddDataProtection()
.SetApplicationName("test_app")
.PersistKeysToAzureBlobStorage(container, "test");
```

I'm going to go through your sample project and try it on my code, I'll tell you the result when I try it.

PD: Thank you very much, I really appreciate your help.

**Comment by ToniGallego87** [comment]
Finally, the problem has been resolved, it was a configuration problem with the application. Specifically, the startup configuration prepare a configuration for three clients (it´s a multiclient app), and one of that client had the same callback url. This was because the callback url is constructed with 'signin-apple/' + configuration id, and the configuration id for two clients was the same by error.

In the end the mistake was silly, sorry for the inconvenience. Thank you very much again!

**Comment by martincostello** [comment]
No problem, glad you managed to resolve it.
