### ISSUE TITLE
legacy apple login flow may leads to account compromised

### ISSUE THREAD

**Issue by royzhang666** [aspnet-contrib/AspNet.Security.OAuth.Providers#713]
### Describe the bug

The current apple login flow may respond client's email, name in clear text, which can be intercepted and changed with the victim's accounts during the apple login process. The application developer have no way to authenticate its validity (considering it is neither encrypted nor protected with signature).

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms

This library has a critical vulnerability that the untrusted email/names be added into the user claims which can lead to customer's account fully compromised.

### Steps To reproduce

1. create a new apple account
2. login to a 3rd party website with Apple OAuth authentication
3. intercept the apple login callback url: /signin-apple, change the email in user parameter to a victim's address
4. continue login, the attacker can pretend to be the victims account in 3rd part website.

### Expected behaviour

exclude the clear text `user` parameter in the callback, or provide an option to client to bypass this parameter.

### Actual behaviour

A cracker can disguise as victim's apple account.

### System information

all systems

### Additional context

https://developer.apple.com/forums/thread/118209

**Comment by martincostello** [comment]
Please provide an example, including any relevant server responses, demonstrating this issue.

As far as I recall from implementing this, the callback is protected by a state parameter as well as a cookie for anti-forgery. Further, the connection is secured with HTTPS which would mitigate MitM scenarios where the response is tampered with.

Also, what do you mean by "legacy" in the issue's title?

**Comment by kevinchalet** [comment]
@royzhang666 thanks for reporting this security issue 👍🏻 

> As far as I recall from implementing this, the callback is protected by a state parameter as well as a cookie for anti-forgery. Further, the connection is secured with HTTPS which would mitigate MitM scenarios where the response is tampered with.

`state` (combined with the antiforgery cookie created by `RemoteAuthenticationHandler`) protects against session fixation and CSRF attacks (i.e where the attacker tries to force the victim to log under an account controlled by the attacker).

The attack here is different: the flow is started and completed by the attacker on his own machine so he has complete access to the `state` and antiforgery cookies. The issue is that on the callback endpoint, we extract an untrusted JSON parameter from the query string containing user data. Yet this parameter can be forged as it's not signed/HMACed: any `ClaimTypes.Email` value can be injected in the resulting `ClaimsIdentity`. And since these claims are always added first (before the claims resolved from `id_token` are added, chances are very high they'll end up overriding the trusted claims as most apps use `identity.FindFirst(...)` when resolving these claims, leading to potential elevation of privilege attacks.

This is a very serious threat so we should confirm it ASAP. Let me know if you need additional guidance to reproduce it.

@royzhang666 submitted a PR to add a new flag allowing to disable addition of claims resolved from this parameter but we should adopt a more radical option and simply remove this unsafe code path and align it with the OpenIddict implementation that doesn't use the non-standard and unsafe `user` parameter (not sure who at Apple thought it was a good idea 🤣)

**Comment by royzhang666** [comment]
yep, I agree with you @kevinchalet, the `user` parameter is a bad design. After reading https://developer.apple.com/forums/thread/118209, I found apple engineer mentioned 3 years ago.

> This will be enhanced soon, and the email or anoymous email will be in id_token.

So I suppose before that time, application developers have to rely on this legacy `user` data to identify user's identity. There's no way to authenticate if the user information is valid or not, cause apple neither encrypt it nor sign it.

**Comment by martincostello** [comment]
After this is dealt with @kevinchalet, I suggest we set up content reports in the two provider repos so we can receive reports like this in the spirit of responsible disclosure easily, rather than them needing to be in public like this before there's any mitigations published.

**Comment by kevinchalet** [comment]
@martincostello definitely a good idea! Here's the SECURITY.md we use in OpenIddict: https://github.com/openiddict/openiddict-core/blob/dev/SECURITY.md (the same message is also present in the main README.md: https://github.com/openiddict/openiddict-core#security-policy). I guess we could reuse it and simply change the email address?

**Comment by martincostello** [comment]
Makes sense, though I don't know what the email address would be.
